title: Site

columns:
  - width: 2/3
    sections:
      pages:
        headline: Site
        type: pages
        templates: 
          - home
          - container
        sortable: true
        image:
          icon: ""
          back: "{{ page.children.listed.sort('date', 'desc').first.color.toColor().html }}"
      
      staticSiteGenerator:
        type: fields
        fields:     
          shelf:
            query: site.index.children.sortBy("date", "desc").filterBy("template", "post").listed
            label: Shelf
            type: pages
            layout: cards
            size: small
            image:
              cover: true
              ratio: 3/2
              icon: ""
              back: "{{ page.color.toColor().html }}"
          # staticSiteGenerator:
          #   label: Generate a static version of the site
          #   type: staticSiteGenerator
  
  - width: 1/3
    sections:
      deployment:
        type: fields
        fields:
          sshDeploy:
            label: Deploy to Server
            type: sshDeploy
            progress: Deploying to server...
            success: Site successfully deployed!
            error: Deployment failed.